import Hero from "@/components/Hero"
import GetRobots from "@/components/GetRobots"
import Intermission from "@/components/Intermission"
import Rarity from "@/components/Rarity"
import Faq from "@/components/Faq"
import { rarityList, typesList } from "@/constants"

export default function Home() {
  return (
    <main>
      <Hero btnText="Mint Robotos" showImages showInventoryCount />
      <GetRobots />
      <Intermission />
      <Rarity
        title="Rarity"
        desc="Each NFT is algorithmically generated by combining 170+ uniqu traits with varying rarity across categories."
        rarityList={rarityList}
        typesList={typesList}
      />
      <Faq />
    </main>
  )
}
