import Image from "next/image"
import { RarityTypeImg } from "./microComponents/images"
import { rarityList, typesList } from "@/constants"

const Rarity = () => {
  return (
    <div className="rarity" id="rarity">
      <div className="container">
        <div className="rarity-card">
          <h3 className="section-title">Rarity</h3>
          <p>
            Each NFT is algorithmically generated by combining 170+ uniqu traits
            with varying rarity across categories.
          </p>

          <div className="rarity-card-grid">
            <div className="rarity-types">
              <h4 className="rarity-title">Types</h4>

              {typesList.map(({ id, title, text }) => (
                <div className="rarity-row" key={id}>
                  <div className="rarity-number">{title}</div>
                  <div className="rarity-row-text">{text}</div>
                </div>
              ))}

              <div className="type-img">
                <Image src={RarityTypeImg} alt="" />
              </div>
            </div>

            <div className="rarity-variations">
              <h4 className="rarity-title">Variations</h4>

              {rarityList.map(({ id, number, text }) => (
                <div className="rarity-row" key={id}>
                  <div className="rarity-number">{number}</div>
                  <div className="rarity-row-text">{text}</div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

export default Rarity
